// ============================================================================
// 🌐 ZONO — Meta Workspace (Batch 6.8) · PUBLISH STORE ADAPTER. Phase 3A (server).
// ----------------------------------------------------------------------------
// Supabase-backed PublishStore (service-role writes; org-scoped). Persists only
// canonical, secret-free state — no token, signed URL, or raw Graph payload. The
// immutable exec content is stored in validation_snapshot jsonb.
// ============================================================================
import "server-only";
import { createServiceRoleClient } from "@/lib/supabase/server";
import type { PublishStore, PublishOperationRow, PublishTargetRow, TargetExecContent } from "./ports";
import type { OperationStatus, TargetStatus, AttemptResult } from "./state";

type Row = Record<string, unknown>;
const db = () => createServiceRoleClient();
const now = () => new Date().toISOString();

const opToDb = (o: PublishOperationRow): Row => ({ id: o.id, org_id: o.orgId, draft_id: o.draftId, draft_version_number: o.draftVersionNumber, content_hash: o.contentHash, requested_by: o.requestedBy, requested_at: o.requestedAt, mode: o.mode, status: o.status, target_count: o.targetCount, successful_target_count: o.successfulTargetCount, failed_target_count: o.failedTargetCount, skipped_target_count: o.skippedTargetCount, started_at: o.startedAt, completed_at: o.completedAt, cancelled_at: o.cancelledAt, cancellation_reason: o.cancellationReason, correlation_id: o.correlationId, idempotency_key: o.idempotencyKey, revision: o.revision, updated_at: now() });
const opFromDb = (d: Row): PublishOperationRow => ({ id: String(d.id), orgId: String(d.org_id), draftId: String(d.draft_id), draftVersionNumber: Number(d.draft_version_number), contentHash: String(d.content_hash), requestedBy: (d.requested_by as string) ?? null, requestedAt: String(d.requested_at), mode: "immediate", status: (d.status as OperationStatus) ?? "created", targetCount: Number(d.target_count ?? 0), successfulTargetCount: Number(d.successful_target_count ?? 0), failedTargetCount: Number(d.failed_target_count ?? 0), skippedTargetCount: Number(d.skipped_target_count ?? 0), startedAt: (d.started_at as string) ?? null, completedAt: (d.completed_at as string) ?? null, cancelledAt: (d.cancelled_at as string) ?? null, cancellationReason: (d.cancellation_reason as string) ?? null, correlationId: String(d.correlation_id ?? ""), idempotencyKey: String(d.idempotency_key ?? ""), revision: Number(d.revision ?? 0) });

const tgToDb = (t: PublishTargetRow): Row => ({ id: t.id, org_id: t.orgId, publish_operation_id: t.operationId, draft_target_id: t.draftTargetId, platform: t.platform, asset_kind: t.assetKind, asset_id: t.assetId, content_kind: t.contentKind, status: t.status, capability_snapshot: { allowed: t.capabilityAllowed }, validation_snapshot: t.exec, idempotency_key: t.idempotencyKey, provider_object_id: t.providerObjectId, provider_container_id: t.providerContainerId, provider_permalink: t.providerPermalink, safe_error_kind: t.safeErrorKind, safe_error_message: t.safeErrorMessage, retryable: t.retryable, retry_class: t.retryClass, started_at: t.startedAt, completed_at: t.completedAt, last_attempt_at: t.lastAttemptAt, revision: t.revision, updated_at: now() });
const tgFromDb = (d: Row): PublishTargetRow => ({ id: String(d.id), orgId: String(d.org_id), operationId: String(d.publish_operation_id), draftTargetId: String(d.draft_target_id), platform: d.platform as PublishTargetRow["platform"], assetKind: d.asset_kind as PublishTargetRow["assetKind"], assetId: String(d.asset_id), contentKind: String(d.content_kind), status: (d.status as TargetStatus) ?? "pending", idempotencyKey: String(d.idempotency_key ?? ""), providerObjectId: (d.provider_object_id as string) ?? null, providerContainerId: (d.provider_container_id as string) ?? null, providerPermalink: (d.provider_permalink as string) ?? null, safeErrorKind: (d.safe_error_kind as string) ?? null, safeErrorMessage: (d.safe_error_message as string) ?? null, retryable: Boolean(d.retryable), retryClass: (d.retry_class as string) ?? null, capabilityAllowed: Boolean((d.capability_snapshot as { allowed?: boolean })?.allowed), exec: (d.validation_snapshot as TargetExecContent) ?? { caption: "", hashtags: [], media: [] }, revision: Number(d.revision ?? 0), startedAt: (d.started_at as string) ?? null, completedAt: (d.completed_at as string) ?? null, lastAttemptAt: (d.last_attempt_at as string) ?? null });

export function createSupabasePublishStore(): PublishStore {
  return {
    async findOperationByIdem(orgId, key) { const r = await db().from("meta_publish_operation" as never).select("*").eq("org_id", orgId).eq("idempotency_key", key).maybeSingle(); return r.data ? opFromDb(r.data as Row) : null; },
    async insertOperation(row) { await db().from("meta_publish_operation" as never).insert(opToDb(row) as never); },
    async getOperation(orgId, id) { const r = await db().from("meta_publish_operation" as never).select("*").eq("org_id", orgId).eq("id", id).maybeSingle(); return r.data ? opFromDb(r.data as Row) : null; },
    async listOperations(orgId) { const r = await db().from("meta_publish_operation" as never).select("*").eq("org_id", orgId).order("requested_at", { ascending: false } as never); return ((r.data as Row[]) ?? []).map(opFromDb); },
    async updateOperation(row) { await db().from("meta_publish_operation" as never).update(opToDb(row) as never).eq("id", row.id); },
    async insertTarget(row) { await db().from("meta_publish_target" as never).insert(tgToDb(row) as never); },
    async getTarget(orgId, id) { const r = await db().from("meta_publish_target" as never).select("*").eq("org_id", orgId).eq("id", id).maybeSingle(); return r.data ? tgFromDb(r.data as Row) : null; },
    async listTargets(orgId, opId) { const r = await db().from("meta_publish_target" as never).select("*").eq("org_id", orgId).eq("publish_operation_id", opId); return ((r.data as Row[]) ?? []).map(tgFromDb); },
    async updateTarget(row) { await db().from("meta_publish_target" as never).update(tgToDb(row) as never).eq("id", row.id); },
    async insertAttempt(row) { await db().from("meta_publish_attempt" as never).insert({ id: row.id, org_id: row.orgId, publish_operation_id: row.operationId, publish_target_id: row.targetId, attempt_number: row.attemptNumber, initiated_by: row.initiatedBy, initiation_kind: row.initiationKind, started_at: row.startedAt, completed_at: row.completedAt, result: row.result, safe_error_kind: row.safeErrorKind, retryable: row.retryable, retry_class: row.retryClass, provider_code_category: row.providerCodeCategory, provider_request_id: row.providerRequestId, correlation_id: row.correlationId, duration_ms: row.durationMs } as never); },
    async listAttempts(orgId, targetId) { const r = await db().from("meta_publish_attempt" as never).select("*").eq("org_id", orgId).eq("publish_target_id", targetId); return ((r.data as Row[]) ?? []).map((a) => ({ id: String(a.id), orgId, operationId: String(a.publish_operation_id), targetId, attemptNumber: Number(a.attempt_number), initiatedBy: (a.initiated_by as string) ?? null, initiationKind: (a.initiation_kind as "initial" | "manual_retry"), startedAt: String(a.started_at), completedAt: (a.completed_at as string) ?? null, result: (a.result as AttemptResult) ?? null, safeErrorKind: (a.safe_error_kind as string) ?? null, retryable: (a.retryable as boolean) ?? null, retryClass: (a.retry_class as string) ?? null, providerCodeCategory: (a.provider_code_category as string) ?? null, providerRequestId: (a.provider_request_id as string) ?? null, correlationId: (a.correlation_id as string) ?? null, durationMs: (a.duration_ms as number) ?? null })); },
    async insertProviderObject(row) { await db().from("meta_provider_object" as never).insert({ id: row.id, org_id: row.orgId, publish_operation_id: row.operationId, publish_target_id: row.targetId, platform: row.platform, asset_id: row.assetId, provider_object_type: row.providerObjectType, external_object_id: row.externalObjectId, external_container_id: row.externalContainerId, permalink: row.permalink, provider_status: row.providerStatus, created_time: row.createdTime } as never); },
  };
}
