// ============================================================================
// 🌐 ZONO — Meta Workspace (Batch 6.9) · INBOX STORE ADAPTER. Phase 3 (server).
// ----------------------------------------------------------------------------
// Supabase-backed InboxStore (service-role writes; org-scoped reads). The inbox is
// a LOCAL projection over the Phase-1 canonical comment data — `listUpdatedThreads`
// reads meta_comment_thread + the root comment (an indexed, bounded, incremental
// query; NO Graph call). Conversation state is a local mutation (never Meta). The
// atomic claim reuses the SKIP LOCKED SQL function. No token / raw payload / Graph
// model is stored. Filters/sort/pagination mirror the pure `search` module in SQL.
// ============================================================================
import "server-only";
import crypto from "node:crypto";
import { createServiceRoleClient } from "@/lib/supabase/server";
import type { InboxStore, InboxSyncJobRow, SyncStateRow, ConversationFull } from "./ports";
import type { ConversationRecord, ConversationState, InboxFilter, InboxSort, InboxPage } from "./domain";
import type { ThreadInput } from "./aggregate";
import type { InboxRow } from "./search";
import { isUnread } from "./state";
import type { MetaPlatform } from "../types";

type Row = Record<string, unknown>;
const db = () => createServiceRoleClient();
const now = () => new Date().toISOString();

const jobToDb = (j: InboxSyncJobRow): Row => ({ id: j.id, org_id: j.orgId, platform: j.platform, status: j.status, priority: j.priority, available_at: j.availableAtIso, cursor: j.cursor, attempt_count: j.attemptCount, max_attempts: j.maxAttempts, retry_budget_remaining: j.retryBudgetRemaining, requeue_count: j.requeueCount, lease_owner: j.leaseOwner, lease_token: j.leaseToken, lease_expires_at: j.leaseExpiresAtIso, heartbeat_at: j.heartbeatAtIso, claimed_at: j.claimedAtIso, started_at: j.startedAtIso, completed_at: j.completedAtIso, next_attempt_at: j.nextAttemptAtIso, last_error_kind: j.lastErrorKind, safe_last_error: j.safeLastError, correlation_id: j.correlationId, idempotency_key: j.idempotencyKey, updated_at: now() });
const jobFromDb = (d: Row): InboxSyncJobRow => ({ id: String(d.id), orgId: String(d.org_id), platform: d.platform as MetaPlatform, status: d.status as InboxSyncJobRow["status"], priority: Number(d.priority ?? 100), availableAtIso: String(d.available_at), cursor: (d.cursor as string) ?? null, attemptCount: Number(d.attempt_count ?? 0), maxAttempts: Number(d.max_attempts ?? 6), retryBudgetRemaining: Number(d.retry_budget_remaining ?? 6), requeueCount: Number(d.requeue_count ?? 0), leaseOwner: (d.lease_owner as string) ?? null, leaseToken: (d.lease_token as string) ?? null, leaseExpiresAtIso: (d.lease_expires_at as string) ?? null, heartbeatAtIso: (d.heartbeat_at as string) ?? null, claimedAtIso: (d.claimed_at as string) ?? null, startedAtIso: (d.started_at as string) ?? null, completedAtIso: (d.completed_at as string) ?? null, nextAttemptAtIso: (d.next_attempt_at as string) ?? null, lastErrorKind: (d.last_error_kind as string) ?? null, safeLastError: (d.safe_last_error as string) ?? null, correlationId: String(d.correlation_id ?? ""), idempotencyKey: String(d.idempotency_key ?? "") });
const rowFromConv = (d: Row, labelIds: string[]): InboxRow => ({ id: String(d.id), status: d.status as InboxRow["status"], platform: d.platform as MetaPlatform, assigneeUserId: (d.assignee_user_id as string) ?? null, unread: Boolean(d.unread), labelIds, participantDisplay: (d.participant_display as string) ?? null, subjectPreview: String(d.subject_preview ?? ""), lastActivityAt: (d.last_activity_at as string) ?? null, priority: Number(d.priority ?? 100) });

export function createSupabaseInboxStore(): InboxStore {
  return {
    async listUpdatedThreads(orgId, platform, sinceIso, limit): Promise<readonly (ThreadInput & { updatedAtIso: string })[]> {
      let q = db().from("meta_comment_thread" as never).select("root_external_comment_id, provider_object_id, reply_count, last_activity_at, updated_at, platform").eq("org_id", orgId).eq("platform", platform).order("updated_at", { ascending: true } as never).limit(limit);
      if (sinceIso) q = q.gt("updated_at", sinceIso);
      const tr = await q; const threads = (tr.data as Row[]) ?? [];
      if (threads.length === 0) return [];
      const roots = threads.map((t) => String(t.root_external_comment_id));
      const cr = await db().from("meta_comment" as never).select("external_comment_id, author_external_id, author_display, message_text").eq("org_id", orgId).eq("platform", platform).in("external_comment_id", roots as never);
      const byId = new Map<string, Row>(); for (const c of (cr.data as Row[]) ?? []) byId.set(String(c.external_comment_id), c);
      return threads.map((t) => { const root = byId.get(String(t.root_external_comment_id)); return { rootExternalId: String(t.root_external_comment_id), platform: t.platform as MetaPlatform, providerObjectId: (t.provider_object_id as string) ?? null, replyCount: Number(t.reply_count ?? 0), lastActivityAt: (t.last_activity_at as string) ?? null, rootAuthorExternalId: (root?.author_external_id as string) ?? null, rootAuthorDisplay: (root?.author_display as string) ?? null, rootMessage: String(root?.message_text ?? ""), updatedAtIso: String(t.updated_at) }; });
    },
    async upsertConversation(orgId, rec: ConversationRecord) {
      const found = await db().from("meta_inbox_conversation" as never).select("id, last_read_at, reply_count, last_activity_at, subject_preview").eq("org_id", orgId).eq("source_kind", rec.sourceKind).eq("source_ref", rec.sourceRef).maybeSingle();
      if (found.data) { const d = found.data as Row; const id = String(d.id); const unread = isUnread(rec.lastActivityAt, (d.last_read_at as string) ?? null); await db().from("meta_inbox_conversation" as never).update({ platform: rec.platform, provider_object_id: rec.providerObjectId, participant_external_id: rec.participantExternalId, participant_display: rec.participantDisplay, subject_preview: rec.subjectPreview, reply_count: rec.replyCount, last_activity_at: rec.lastActivityAt, unread, updated_at: now() } as never).eq("id", id); return { id, created: false, changed: true }; }
      const id = crypto.randomUUID(); await db().from("meta_inbox_conversation" as never).insert({ id, org_id: orgId, source_kind: rec.sourceKind, source_ref: rec.sourceRef, platform: rec.platform, provider_object_id: rec.providerObjectId, participant_external_id: rec.participantExternalId, participant_display: rec.participantDisplay, subject_preview: rec.subjectPreview, reply_count: rec.replyCount, last_activity_at: rec.lastActivityAt, unread: true, status: "open", created_at: now(), updated_at: now() } as never); return { id, created: true, changed: true };
    },
    async getSyncState(orgId, platform) { const r = await db().from("meta_inbox_sync_state" as never).select("*").eq("org_id", orgId).eq("platform", platform).maybeSingle(); if (!r.data) return null; const d = r.data as Row; return { platform, cursorUpdatedAtIso: (d.cursor_updated_at as string) ?? null, lastSyncedAtIso: (d.last_synced_at as string) ?? null, syncedCount: Number(d.synced_count ?? 0) }; },
    async upsertSyncState(orgId, row: SyncStateRow) { const found = await db().from("meta_inbox_sync_state" as never).select("id").eq("org_id", orgId).eq("platform", row.platform).maybeSingle(); const body = { org_id: orgId, platform: row.platform, cursor_updated_at: row.cursorUpdatedAtIso, last_synced_at: row.lastSyncedAtIso, synced_count: row.syncedCount, updated_at: now() }; if (found.data) await db().from("meta_inbox_sync_state" as never).update(body as never).eq("id", String((found.data as { id: string }).id)); else await db().from("meta_inbox_sync_state" as never).insert({ id: crypto.randomUUID(), ...body, created_at: now() } as never); },
    async getConversation(orgId, id): Promise<ConversationFull | null> { const r = await db().from("meta_inbox_conversation" as never).select("*").eq("org_id", orgId).eq("id", id).maybeSingle(); if (!r.data) return null; const d = r.data as Row; return { id: String(d.id), sourceKind: (d.source_kind as ConversationFull["sourceKind"]) ?? "comment_thread", sourceRef: String(d.source_ref), platform: d.platform as MetaPlatform, providerObjectId: (d.provider_object_id as string) ?? null, participantExternalId: (d.participant_external_id as string) ?? null, participantDisplay: (d.participant_display as string) ?? null, subjectPreview: String(d.subject_preview ?? ""), replyCount: Number(d.reply_count ?? 0), lastActivityAt: (d.last_activity_at as string) ?? null, status: d.status as ConversationState["status"], snoozedUntil: (d.snoozed_until as string) ?? null, lastReadAt: (d.last_read_at as string) ?? null, assigneeUserId: (d.assignee_user_id as string) ?? null, priority: Number(d.priority ?? 100) }; },
    async updateConversationState(orgId, id, state) { const body: Row = { updated_at: now() }; if (state.status !== undefined) body.status = state.status; if (state.snoozedUntil !== undefined) body.snoozed_until = state.snoozedUntil; if (state.lastReadAt !== undefined) body.last_read_at = state.lastReadAt; if (state.assigneeUserId !== undefined) body.assignee_user_id = state.assigneeUserId; if (state.priority !== undefined) body.priority = state.priority; if ((state as { unread?: boolean }).unread !== undefined) body.unread = (state as { unread?: boolean }).unread; await db().from("meta_inbox_conversation" as never).update(body as never).eq("org_id", orgId).eq("id", id); },
    async recordAssignment(orgId, conversationId, assigneeUserId, assignedBy) { await db().from("meta_inbox_assignment" as never).insert({ id: crypto.randomUUID(), org_id: orgId, conversation_id: conversationId, assignee_user_id: assigneeUserId, assigned_by: assignedBy, assigned_at: now() } as never); },
    async listLabels(orgId) { const r = await db().from("meta_inbox_label" as never).select("id, name, color").eq("org_id", orgId).order("name", { ascending: true } as never); return ((r.data as Row[]) ?? []).map((d) => ({ id: String(d.id), name: String(d.name), color: (d.color as string) ?? null })); },
    async createLabel(orgId, name, color) { const found = await db().from("meta_inbox_label" as never).select("id").eq("org_id", orgId).eq("name", name).maybeSingle(); if (found.data) return String((found.data as { id: string }).id); const id = crypto.randomUUID(); await db().from("meta_inbox_label" as never).insert({ id, org_id: orgId, name, color, created_at: now() } as never); return id; },
    async addLabel(orgId, conversationId, labelId) { await db().from("meta_inbox_conversation_label" as never).upsert({ org_id: orgId, conversation_id: conversationId, label_id: labelId, created_at: now() } as never, { onConflict: "conversation_id,label_id", ignoreDuplicates: true } as never); },
    async removeLabel(orgId, conversationId, labelId) { await db().from("meta_inbox_conversation_label" as never).delete().eq("org_id", orgId).eq("conversation_id", conversationId).eq("label_id", labelId); },
    async listConversations(orgId, filter: InboxFilter, sort: InboxSort, page: InboxPage) {
      let ids: string[] | null = null;
      if (filter.labelId) { const lr = await db().from("meta_inbox_conversation_label" as never).select("conversation_id").eq("org_id", orgId).eq("label_id", filter.labelId); ids = ((lr.data as Row[]) ?? []).map((x) => String(x.conversation_id)); if (ids.length === 0) return { items: [], total: 0 }; }
      const build = () => { let q = db().from("meta_inbox_conversation" as never).select("*", { count: "exact" } as never).eq("org_id", orgId); if (filter.status) q = q.eq("status", filter.status); if (filter.platform) q = q.eq("platform", filter.platform); if (filter.assigneeUserId !== undefined) q = filter.assigneeUserId === null ? q.is("assignee_user_id", null) : q.eq("assignee_user_id", filter.assigneeUserId); if (filter.unreadOnly) q = q.eq("unread", true); if (filter.query && filter.query.trim()) { const s = filter.query.trim().replace(/[%_]/g, ""); q = q.or(`participant_display.ilike.%${s}%,subject_preview.ilike.%${s}%`); } if (ids) q = q.in("id", ids as never); return q; };
      const asc = sort === "oldest"; const col = sort === "priority" ? "priority" : "last_activity_at";
      const limit = Math.max(1, Math.min(100, page.limit)); const offset = Math.max(0, page.offset);
      const r = await build().order(col, { ascending: asc } as never).range(offset, offset + limit - 1);
      const rows = (r.data as Row[]) ?? [];
      const labelMap = new Map<string, string[]>();
      if (rows.length) { const lr = await db().from("meta_inbox_conversation_label" as never).select("conversation_id, label_id").eq("org_id", orgId).in("conversation_id", rows.map((x) => String(x.id)) as never); for (const l of (lr.data as Row[]) ?? []) { const k = String(l.conversation_id); labelMap.set(k, [...(labelMap.get(k) ?? []), String(l.label_id)]); } }
      return { items: rows.map((d) => rowFromConv(d, labelMap.get(String(d.id)) ?? [])), total: (r.count as number) ?? rows.length };
    },
    async countUnread(orgId) { const r = await db().from("meta_inbox_conversation" as never).select("id", { count: "exact", head: true } as never).eq("org_id", orgId).eq("unread", true).eq("status", "open"); return (r.count as number) ?? 0; },
    async insertJob(row) { await db().from("meta_inbox_sync_job" as never).insert({ ...jobToDb(row), created_at: now() } as never); },
    async getJob(orgId, id) { const r = await db().from("meta_inbox_sync_job" as never).select("*").eq("org_id", orgId).eq("id", id).maybeSingle(); return r.data ? jobFromDb(r.data as Row) : null; },
    async findJobByIdem(orgId, key) { const r = await db().from("meta_inbox_sync_job" as never).select("*").eq("org_id", orgId).eq("idempotency_key", key).maybeSingle(); return r.data ? jobFromDb(r.data as Row) : null; },
    async findActiveJob(orgId, platform) { const r = await db().from("meta_inbox_sync_job" as never).select("*").eq("org_id", orgId).eq("platform", platform).in("status", ["scheduled", "available", "claimed", "executing", "retry_wait"] as never).maybeSingle(); return r.data ? jobFromDb(r.data as Row) : null; },
    async updateJob(row) { await db().from("meta_inbox_sync_job" as never).update(jobToDb(row) as never).eq("id", row.id); },
    async claimDueJobs(args) { const r = await db().rpc("meta_inbox_claim_due" as never, { p_now: new Date(args.nowMs).toISOString(), p_limit: args.limit, p_per_org_max: args.perOrgMax, p_lease_owner: args.leaseOwner, p_lease_seconds: args.leaseSeconds } as never); return ((r.data as unknown as Row[]) ?? []).map(jobFromDb); },
    async findStaleJobs(nowMs, limit) { const r = await db().from("meta_inbox_sync_job" as never).select("*").in("status", ["claimed", "executing"] as never).lte("lease_expires_at", new Date(nowMs).toISOString()).limit(limit); return ((r.data as Row[]) ?? []).map(jobFromDb); },
    async countInFlight() { const r = await db().from("meta_inbox_sync_job" as never).select("org_id").in("status", ["claimed", "executing"] as never); const rows = (r.data as Row[]) ?? []; const per: Record<string, number> = {}; for (const x of rows) { const o = String(x.org_id); per[o] = (per[o] ?? 0) + 1; } return { global: rows.length, perOrg: per }; },
    async queueHealth(orgId, nowMs) { let q = db().from("meta_inbox_sync_job" as never).select("status, available_at"); if (orgId) q = q.eq("org_id", orgId); const r = await q; const rows = (r.data as Row[]) ?? []; const by: Record<string, number> = {}; let oldest: number | null = null; for (const x of rows) { const s = String(x.status); by[s] = (by[s] ?? 0) + 1; if ((s === "scheduled" || s === "available" || s === "retry_wait") && x.available_at) { const due = Date.parse(String(x.available_at)); if (due <= nowMs) { const age = nowMs - due; if (oldest == null || age > oldest) oldest = age; } } } return { byStatus: by, deadLetter: by.dead_letter ?? 0, oldestDueMs: oldest }; },
  };
}
