// ============================================================================
// 🌐 ZONO — Meta Workspace (Batch 6.9) · ENGAGEMENT STORE ADAPTER. Phase 1 (server).
// ----------------------------------------------------------------------------
// Supabase-backed EngagementStore (service-role writes; org-scoped reads). Persists
// only canonical, secret-free state (comments are public content). Dedup is
// enforced by the unique (org, platform, external_comment_id) constraint; a re-sync
// updates the row in place. The atomic claim reuses the SKIP LOCKED SQL function.
// Moderation actions never auto-execute here — the engine gates on approval.
// ============================================================================
import "server-only";
import crypto from "node:crypto";
import { createServiceRoleClient } from "@/lib/supabase/server";
import type { EngagementStore, CommentJobRow, ModerationActionRow, ObjectProviderRef, CommentProviderRef, CommentJobKind } from "./ports";
import type { CommentRecord, ThreadRollup, ModerationKind } from "./domain";
import type { MetaPlatform } from "../types";

type Row = Record<string, unknown>;
const db = () => createServiceRoleClient();
const now = () => new Date().toISOString();

const jobToDb = (j: CommentJobRow): Row => ({ id: j.id, org_id: j.orgId, job_kind: j.jobKind, provider_object_id: j.providerObjectId, target_comment_id: j.targetCommentId, engagement_action_id: j.engagementActionId, webhook_event_id: j.webhookEventId, status: j.status, priority: j.priority, available_at: j.availableAtIso, cursor: j.cursor, attempt_count: j.attemptCount, max_attempts: j.maxAttempts, retry_budget_remaining: j.retryBudgetRemaining, requeue_count: j.requeueCount, lease_owner: j.leaseOwner, lease_token: j.leaseToken, lease_expires_at: j.leaseExpiresAtIso, heartbeat_at: j.heartbeatAtIso, claimed_at: j.claimedAtIso, started_at: j.startedAtIso, completed_at: j.completedAtIso, next_attempt_at: j.nextAttemptAtIso, last_error_kind: j.lastErrorKind, safe_last_error: j.safeLastError, correlation_id: j.correlationId, idempotency_key: j.idempotencyKey, updated_at: now() });
const jobFromDb = (d: Row): CommentJobRow => ({ id: String(d.id), orgId: String(d.org_id), jobKind: d.job_kind as CommentJobKind, providerObjectId: (d.provider_object_id as string) ?? null, targetCommentId: (d.target_comment_id as string) ?? null, engagementActionId: (d.engagement_action_id as string) ?? null, webhookEventId: (d.webhook_event_id as string) ?? null, status: d.status as CommentJobRow["status"], priority: Number(d.priority ?? 100), availableAtIso: String(d.available_at), cursor: (d.cursor as string) ?? null, attemptCount: Number(d.attempt_count ?? 0), maxAttempts: Number(d.max_attempts ?? 6), retryBudgetRemaining: Number(d.retry_budget_remaining ?? 6), requeueCount: Number(d.requeue_count ?? 0), leaseOwner: (d.lease_owner as string) ?? null, leaseToken: (d.lease_token as string) ?? null, leaseExpiresAtIso: (d.lease_expires_at as string) ?? null, heartbeatAtIso: (d.heartbeat_at as string) ?? null, claimedAtIso: (d.claimed_at as string) ?? null, startedAtIso: (d.started_at as string) ?? null, completedAtIso: (d.completed_at as string) ?? null, nextAttemptAtIso: (d.next_attempt_at as string) ?? null, lastErrorKind: (d.last_error_kind as string) ?? null, safeLastError: (d.safe_last_error as string) ?? null, correlationId: String(d.correlation_id ?? ""), idempotencyKey: String(d.idempotency_key ?? "") });

const actionToDb = (a: ModerationActionRow): Row => ({ id: a.id, org_id: a.orgId, action_kind: a.actionKind, platform: a.platform, target_comment_id: a.targetCommentId, provider_object_id: a.providerObjectId, reply_text: a.replyText, approval_state: a.approvalState, status: a.status, requested_by: a.requestedBy, approved_by: a.approvedBy, provider_result_id: a.providerResultId, safe_error_kind: a.safeErrorKind, safe_error_message: a.safeErrorMessage, retryable: a.retryable, retry_class: a.retryClass, attempt_count: a.attemptCount, correlation_id: a.correlationId, idempotency_key: a.idempotencyKey, executed_at: a.executedAtIso, updated_at: now() });
const actionFromDb = (d: Row): ModerationActionRow => ({ id: String(d.id), orgId: String(d.org_id), actionKind: d.action_kind as ModerationKind, platform: d.platform as MetaPlatform, targetCommentId: String(d.target_comment_id), providerObjectId: (d.provider_object_id as string) ?? null, replyText: (d.reply_text as string) ?? null, approvalState: d.approval_state as ModerationActionRow["approvalState"], status: d.status as ModerationActionRow["status"], requestedBy: (d.requested_by as string) ?? null, approvedBy: (d.approved_by as string) ?? null, providerResultId: (d.provider_result_id as string) ?? null, safeErrorKind: (d.safe_error_kind as string) ?? null, safeErrorMessage: (d.safe_error_message as string) ?? null, retryable: Boolean(d.retryable), retryClass: (d.retry_class as string) ?? null, attemptCount: Number(d.attempt_count ?? 0), correlationId: String(d.correlation_id ?? ""), idempotencyKey: String(d.idempotency_key ?? ""), executedAtIso: (d.executed_at as string) ?? null });

const commentToDb = (orgId: string, providerObjectId: string | null, c: CommentRecord): Row => ({ org_id: orgId, provider_object_id: providerObjectId, platform: c.platform, external_comment_id: c.externalId, external_parent_comment_id: c.parentExternalId, root_external_comment_id: c.rootExternalId, author_external_id: c.authorExternalId, author_display: c.authorDisplay, message_text: c.message, attachments_safe: c.attachmentsSafe, like_count: c.likeCount, reply_count: c.replyCount, status: c.status, is_from_page: c.isFromPage, provider_created_at: c.providerCreatedAt, provider_updated_at: c.providerUpdatedAt, content_fingerprint: c.contentFingerprint, last_synced_at: now(), updated_at: now() });

export function createSupabaseEngagementStore(): EngagementStore {
  return {
    async upsertComment(orgId, providerObjectId, rec) {
      const found = await db().from("meta_comment" as never).select("id").eq("org_id", orgId).eq("platform", rec.platform).eq("external_comment_id", rec.externalId).maybeSingle();
      if (found.data) { const id = String((found.data as { id: string }).id); await db().from("meta_comment" as never).update(commentToDb(orgId, providerObjectId, rec) as never).eq("id", id); return { id, changed: true }; }
      const id = crypto.randomUUID(); await db().from("meta_comment" as never).insert({ id, ...commentToDb(orgId, providerObjectId, rec), ingested_at: now(), created_at: now() } as never); return { id, changed: true };
    },
    async getComment(orgId, id) { const r = await db().from("meta_comment" as never).select("id, external_comment_id, platform, status, provider_object_id").eq("org_id", orgId).eq("id", id).maybeSingle(); if (!r.data) return null; const d = r.data as Row; return { id: String(d.id), externalId: String(d.external_comment_id), platform: d.platform as MetaPlatform, status: String(d.status), providerObjectId: (d.provider_object_id as string) ?? null }; },
    async getCommentByExternalId(orgId, platform, externalId) { const r = await db().from("meta_comment" as never).select("id, content_fingerprint").eq("org_id", orgId).eq("platform", platform).eq("external_comment_id", externalId).maybeSingle(); if (!r.data) return null; const d = r.data as Row; return { id: String(d.id), contentFingerprint: String(d.content_fingerprint ?? "") }; },
    async listCommentsForObject(orgId, providerObjectId) { const r = await db().from("meta_comment" as never).select("*").eq("org_id", orgId).eq("provider_object_id", providerObjectId).order("provider_created_at", { ascending: true } as never); return ((r.data as Row[]) ?? []).map((d) => ({ externalId: String(d.external_comment_id), parentExternalId: (d.external_parent_comment_id as string) ?? null, rootExternalId: String(d.root_external_comment_id ?? d.external_comment_id), platform: d.platform as MetaPlatform, authorExternalId: (d.author_external_id as string) ?? null, authorDisplay: (d.author_display as string) ?? null, message: String(d.message_text ?? ""), likeCount: Number(d.like_count ?? 0), replyCount: Number(d.reply_count ?? 0), status: d.status as CommentRecord["status"], isFromPage: Boolean(d.is_from_page), providerCreatedAt: (d.provider_created_at as string) ?? null, providerUpdatedAt: (d.provider_updated_at as string) ?? null, attachmentsSafe: (d.attachments_safe as { kind: string }[]) ?? [], contentFingerprint: String(d.content_fingerprint ?? "") })); },
    async setCommentStatus(orgId, id, status) { await db().from("meta_comment" as never).update({ status, updated_at: now() } as never).eq("org_id", orgId).eq("id", id); },
    async upsertThread(orgId, providerObjectId, platform, roll: ThreadRollup) {
      const found = await db().from("meta_comment_thread" as never).select("id").eq("org_id", orgId).eq("root_external_comment_id", roll.rootExternalId).maybeSingle();
      const body = { org_id: orgId, provider_object_id: providerObjectId, platform, root_external_comment_id: roll.rootExternalId, reply_count: roll.replyCount, last_activity_at: roll.lastActivityAt, page_replied: roll.pageReplied, has_unaddressed: roll.hasUnaddressed, updated_at: now() };
      if (found.data) await db().from("meta_comment_thread" as never).update(body as never).eq("id", String((found.data as { id: string }).id));
      else await db().from("meta_comment_thread" as never).insert({ id: crypto.randomUUID(), ...body, created_at: now() } as never);
    },
    async objectRef(orgId, providerObjectId): Promise<ObjectProviderRef | null> { const r = await db().from("meta_provider_object" as never).select("external_object_id, asset_id, platform").eq("org_id", orgId).eq("id", providerObjectId).maybeSingle(); if (!r.data) return null; const d = r.data as Row; return { objectExternalId: String(d.external_object_id), assetId: String(d.asset_id), platform: d.platform as MetaPlatform }; },
    async insertAction(row) { await db().from("meta_engagement_action" as never).insert({ ...actionToDb(row), created_at: now() } as never); },
    async getAction(orgId, id) { const r = await db().from("meta_engagement_action" as never).select("*").eq("org_id", orgId).eq("id", id).maybeSingle(); return r.data ? actionFromDb(r.data as Row) : null; },
    async findActiveAction(orgId, targetCommentId, actionKind) { const r = await db().from("meta_engagement_action" as never).select("*").eq("org_id", orgId).eq("target_comment_id", targetCommentId).eq("action_kind", actionKind).in("status", ["pending", "ready", "executing", "provider_processing"] as never).maybeSingle(); return r.data ? actionFromDb(r.data as Row) : null; },
    async updateAction(row) { await db().from("meta_engagement_action" as never).update(actionToDb(row) as never).eq("id", row.id); },
    async moderationRef(orgId, actionId): Promise<{ action: ModerationActionRow; ref: CommentProviderRef } | null> {
      const a = await this.getAction(orgId, actionId); if (!a) return null;
      const c = await db().from("meta_comment" as never).select("external_comment_id, platform, status, provider_object_id").eq("org_id", orgId).eq("id", a.targetCommentId).maybeSingle();
      if (!c.data) return null; const cd = c.data as Row;
      let objectExternalId: string | null = null, assetId = "";
      if (cd.provider_object_id) { const ref = await this.objectRef(orgId, String(cd.provider_object_id)); if (ref) { objectExternalId = ref.objectExternalId; assetId = ref.assetId; } }
      return { action: a, ref: { commentExternalId: String(cd.external_comment_id), platform: cd.platform as MetaPlatform, objectExternalId, assetId, status: String(cd.status) } };
    },
    async insertJob(row) { await db().from("meta_comment_ingestion_job" as never).insert({ ...jobToDb(row), created_at: now() } as never); },
    async getJob(orgId, id) { const r = await db().from("meta_comment_ingestion_job" as never).select("*").eq("org_id", orgId).eq("id", id).maybeSingle(); return r.data ? jobFromDb(r.data as Row) : null; },
    async findJobByIdem(orgId, key) { const r = await db().from("meta_comment_ingestion_job" as never).select("*").eq("org_id", orgId).eq("idempotency_key", key).maybeSingle(); return r.data ? jobFromDb(r.data as Row) : null; },
    async findActiveJob(orgId, jobKind, anchorId) { const r = await db().from("meta_comment_ingestion_job" as never).select("*").eq("org_id", orgId).eq("job_kind", jobKind).in("status", ["scheduled", "available", "claimed", "executing", "retry_wait"] as never).or(`engagement_action_id.eq.${anchorId},target_comment_id.eq.${anchorId},provider_object_id.eq.${anchorId}`).maybeSingle(); return r.data ? jobFromDb(r.data as Row) : null; },
    async updateJob(row) { await db().from("meta_comment_ingestion_job" as never).update(jobToDb(row) as never).eq("id", row.id); },
    async claimDueJobs(args) { const r = await db().rpc("meta_comment_claim_due" as never, { p_now: new Date(args.nowMs).toISOString(), p_limit: args.limit, p_per_org_max: args.perOrgMax, p_lease_owner: args.leaseOwner, p_lease_seconds: args.leaseSeconds } as never); return ((r.data as unknown as Row[]) ?? []).map(jobFromDb); },
    async findStaleJobs(nowMs, limit) { const r = await db().from("meta_comment_ingestion_job" as never).select("*").in("status", ["claimed", "executing"] as never).lte("lease_expires_at", new Date(nowMs).toISOString()).limit(limit); return ((r.data as Row[]) ?? []).map(jobFromDb); },
    async countInFlight() { const r = await db().from("meta_comment_ingestion_job" as never).select("org_id").in("status", ["claimed", "executing"] as never); const rows = (r.data as Row[]) ?? []; const per: Record<string, number> = {}; for (const x of rows) { const o = String(x.org_id); per[o] = (per[o] ?? 0) + 1; } return { global: rows.length, perOrg: per }; },
    async queueHealth(orgId, nowMs) { let q = db().from("meta_comment_ingestion_job" as never).select("status, available_at"); if (orgId) q = q.eq("org_id", orgId); const r = await q; const rows = (r.data as Row[]) ?? []; const by: Record<string, number> = {}; let oldest: number | null = null; for (const x of rows) { const s = String(x.status); by[s] = (by[s] ?? 0) + 1; if ((s === "scheduled" || s === "available" || s === "retry_wait") && x.available_at) { const due = Date.parse(String(x.available_at)); if (due <= nowMs) { const age = nowMs - due; if (oldest == null || age > oldest) oldest = age; } } } return { byStatus: by, deadLetter: by.dead_letter ?? 0, oldestDueMs: oldest }; },
  };
}
