// ============================================================================
// 🌐 ZONO — Meta Workspace (Batch 6.8) · RECONCILIATION STORE ADAPTER. Phase 3C (server).
// ----------------------------------------------------------------------------
// Supabase-backed ReconcileStore (service-role writes; org-scoped reads). Persists
// only canonical, secret-free state. The atomic claim reuses the SKIP LOCKED SQL
// function (same convention as Phase 3B). Object-state is append-only; discrepancy
// evidence accrues on one live row per (target,type). Safe repairs mutate ONLY
// local publishing state — never provider content, never immutable history.
// ============================================================================
import "server-only";
import crypto from "node:crypto";
import { createServiceRoleClient } from "@/lib/supabase/server";
import type { ReconcileStore, ReconcileJobRow, ReconcileAttemptRow, ObjectStateRow, DiscrepancyRow, TargetSnapshot } from "./ports";
import type { ReconcileJobKind } from "./decision";

type Row = Record<string, unknown>;
const db = () => createServiceRoleClient();
const now = () => new Date().toISOString();

const jobToDb = (j: ReconcileJobRow): Row => ({ id: j.id, org_id: j.orgId, job_kind: j.jobKind, publish_operation_id: j.publishOperationId, publish_target_id: j.publishTargetId, provider_object_id: j.providerObjectId, dead_letter_id: j.deadLetterId, webhook_event_id: j.webhookEventId, status: j.status, reason: j.reason, priority: j.priority, available_at: j.availableAtIso, attempt_count: j.attemptCount, max_attempts: j.maxAttempts, confirmation_count: j.confirmationCount, lease_owner: j.leaseOwner, lease_token: j.leaseToken, lease_expires_at: j.leaseExpiresAtIso, heartbeat_at: j.heartbeatAtIso, claimed_at: j.claimedAtIso, started_at: j.startedAtIso, completed_at: j.completedAtIso, next_attempt_at: j.nextAttemptAtIso, safe_error_kind: j.safeErrorKind, correlation_id: j.correlationId, idempotency_key: j.idempotencyKey, updated_at: now() });
const jobFromDb = (d: Row): ReconcileJobRow => ({ id: String(d.id), orgId: String(d.org_id), jobKind: d.job_kind as ReconcileJobKind, publishOperationId: (d.publish_operation_id as string) ?? null, publishTargetId: (d.publish_target_id as string) ?? null, providerObjectId: (d.provider_object_id as string) ?? null, deadLetterId: (d.dead_letter_id as string) ?? null, webhookEventId: (d.webhook_event_id as string) ?? null, status: d.status as ReconcileJobRow["status"], reason: (d.reason as string) ?? null, priority: Number(d.priority ?? 100), availableAtIso: String(d.available_at), attemptCount: Number(d.attempt_count ?? 0), maxAttempts: Number(d.max_attempts ?? 6), confirmationCount: Number(d.confirmation_count ?? 0), leaseOwner: (d.lease_owner as string) ?? null, leaseToken: (d.lease_token as string) ?? null, leaseExpiresAtIso: (d.lease_expires_at as string) ?? null, heartbeatAtIso: (d.heartbeat_at as string) ?? null, claimedAtIso: (d.claimed_at as string) ?? null, startedAtIso: (d.started_at as string) ?? null, completedAtIso: (d.completed_at as string) ?? null, nextAttemptAtIso: (d.next_attempt_at as string) ?? null, safeErrorKind: (d.safe_error_kind as string) ?? null, correlationId: String(d.correlation_id ?? ""), idempotencyKey: String(d.idempotency_key ?? "") });

const discFromDb = (d: Row): DiscrepancyRow => ({ id: String(d.id), orgId: String(d.org_id), publishOperationId: (d.publish_operation_id as string) ?? null, publishTargetId: (d.publish_target_id as string) ?? null, providerObjectId: (d.provider_object_id as string) ?? null, discrepancyType: d.discrepancy_type as DiscrepancyRow["discrepancyType"], severity: d.severity as DiscrepancyRow["severity"], status: d.status as DiscrepancyRow["status"], detectedAtIso: String(d.detected_at), lastConfirmedAtIso: (d.last_confirmed_at as string) ?? null, evidenceCount: Number(d.evidence_count ?? 1), safeSummary: (d.safe_summary as string) ?? null, autoRepairable: Boolean(d.auto_repairable), repairedAtIso: (d.repaired_at as string) ?? null, repairedBy: (d.repaired_by as string) ?? null, resolution: (d.resolution as string) ?? null, resolvedBy: (d.resolved_by as string) ?? null, resolutionReason: (d.resolution_reason as string) ?? null });
const stateFromDb = (d: Row): ObjectStateRow => ({ id: String(d.id), orgId: String(d.org_id), providerObjectId: String(d.provider_object_id), observedAtIso: String(d.observed_at), state: d.state as ObjectStateRow["state"], visibilityState: (d.visibility_state as string) ?? null, providerCreatedTime: (d.provider_created_time as string) ?? null, providerUpdatedTime: (d.provider_updated_time as string) ?? null, permalink: (d.permalink as string) ?? null, externalParentId: (d.external_parent_id as string) ?? null, evidenceKind: d.evidence_kind as ObjectStateRow["evidenceKind"], sourceEventId: (d.source_event_id as string) ?? null, sourceReconciliationAttemptId: (d.source_reconciliation_attempt_id as string) ?? null, contentFingerprint: (d.content_fingerprint as string) ?? null, safeMetadata: (d.safe_metadata as Record<string, unknown>) ?? {} });

export function createSupabaseReconcileStore(): ReconcileStore {
  return {
    async insertJob(row) { await db().from("meta_reconciliation_job" as never).insert({ ...jobToDb(row), created_at: now() } as never); },
    async getJob(orgId, id) { const r = await db().from("meta_reconciliation_job" as never).select("*").eq("org_id", orgId).eq("id", id).maybeSingle(); return r.data ? jobFromDb(r.data as Row) : null; },
    async findJobByIdem(orgId, key) { const r = await db().from("meta_reconciliation_job" as never).select("*").eq("org_id", orgId).eq("idempotency_key", key).maybeSingle(); return r.data ? jobFromDb(r.data as Row) : null; },
    async findActiveJob(orgId, jobKind, anchorId) {
      const r = await db().from("meta_reconciliation_job" as never).select("*").eq("org_id", orgId).eq("job_kind", jobKind).in("status", ["scheduled", "available", "claimed", "executing", "retry_wait"] as never).or(`provider_object_id.eq.${anchorId},publish_target_id.eq.${anchorId},publish_operation_id.eq.${anchorId}`).maybeSingle();
      return r.data ? jobFromDb(r.data as Row) : null;
    },
    async updateJob(row) { await db().from("meta_reconciliation_job" as never).update(jobToDb(row) as never).eq("id", row.id); },
    async claimDueJobs(args) { const r = await db().rpc("meta_reconcile_claim_due" as never, { p_now: new Date(args.nowMs).toISOString(), p_limit: args.limit, p_per_org_max: args.perOrgMax, p_lease_owner: args.leaseOwner, p_lease_seconds: args.leaseSeconds } as never); return ((r.data as unknown as Row[]) ?? []).map(jobFromDb); },
    async findStaleJobs(nowMs, limit) { const r = await db().from("meta_reconciliation_job" as never).select("*").in("status", ["claimed", "executing"] as never).lte("lease_expires_at", new Date(nowMs).toISOString()).limit(limit); return ((r.data as Row[]) ?? []).map(jobFromDb); },
    async countInFlight() { const r = await db().from("meta_reconciliation_job" as never).select("org_id").in("status", ["claimed", "executing"] as never); const rows = (r.data as Row[]) ?? []; const per: Record<string, number> = {}; for (const x of rows) { const o = String(x.org_id); per[o] = (per[o] ?? 0) + 1; } return { global: rows.length, perOrg: per }; },
    async insertAttempt(row: ReconcileAttemptRow) { await db().from("meta_reconciliation_attempt" as never).insert({ id: row.id, org_id: row.orgId, reconciliation_job_id: row.reconciliationJobId, publish_operation_id: row.publishOperationId, publish_target_id: row.publishTargetId, provider_object_id: row.providerObjectId, attempt_number: row.attemptNumber, initiated_by: row.initiatedBy, initiation_kind: row.initiationKind, started_at: row.startedAtIso, completed_at: row.completedAtIso, result: row.result, observed_provider_state: row.observedProviderState, safe_error_kind: row.safeErrorKind, retry_class: row.retryClass, provider_request_id: row.providerRequestId, duration_ms: row.durationMs, correlation_id: row.correlationId } as never); },
    async listAttempts(orgId, jobId) { const r = await db().from("meta_reconciliation_attempt" as never).select("*").eq("org_id", orgId).eq("reconciliation_job_id", jobId).order("attempt_number", { ascending: true } as never); return ((r.data as Row[]) ?? []).map((a) => ({ id: String(a.id), orgId, reconciliationJobId: jobId, publishOperationId: (a.publish_operation_id as string) ?? null, publishTargetId: (a.publish_target_id as string) ?? null, providerObjectId: (a.provider_object_id as string) ?? null, attemptNumber: Number(a.attempt_number), initiatedBy: (a.initiated_by as string) ?? null, initiationKind: a.initiation_kind as ReconcileAttemptRow["initiationKind"], startedAtIso: String(a.started_at), completedAtIso: (a.completed_at as string) ?? null, result: (a.result as string) ?? null, observedProviderState: (a.observed_provider_state as string) ?? null, safeErrorKind: (a.safe_error_kind as string) ?? null, retryClass: (a.retry_class as string) ?? null, providerRequestId: (a.provider_request_id as string) ?? null, durationMs: (a.duration_ms as number) ?? null, correlationId: (a.correlation_id as string) ?? null })); },
    async appendObjectState(row) { await db().from("meta_provider_object_state" as never).insert({ id: row.id, org_id: row.orgId, provider_object_id: row.providerObjectId, observed_at: row.observedAtIso, state: row.state, visibility_state: row.visibilityState, provider_created_time: row.providerCreatedTime, provider_updated_time: row.providerUpdatedTime, permalink: row.permalink, external_parent_id: row.externalParentId, evidence_kind: row.evidenceKind, source_event_id: row.sourceEventId, source_reconciliation_attempt_id: row.sourceReconciliationAttemptId, content_fingerprint: row.contentFingerprint, safe_metadata: row.safeMetadata } as never); },
    async listObjectStates(orgId, providerObjectId) { const r = await db().from("meta_provider_object_state" as never).select("*").eq("org_id", orgId).eq("provider_object_id", providerObjectId).order("observed_at", { ascending: true } as never); return ((r.data as Row[]) ?? []).map(stateFromDb); },
    async upsertDiscrepancy(row) {
      const found = await db().from("meta_publish_discrepancy" as never).select("*").eq("org_id", row.orgId).eq("publish_target_id", (row.publishTargetId ?? "") as never).eq("discrepancy_type", row.discrepancyType).maybeSingle();
      if (found.data) { const cur = discFromDb(found.data as Row); const next = { ...cur, evidenceCount: cur.evidenceCount + 1, lastConfirmedAtIso: now(), severity: row.severity, status: cur.status === "resolved" || cur.status === "false_positive" ? "open" : cur.status }; await db().from("meta_publish_discrepancy" as never).update({ evidence_count: next.evidenceCount, last_confirmed_at: next.lastConfirmedAtIso, severity: next.severity, status: next.status, updated_at: now() } as never).eq("id", cur.id); return next; }
      await db().from("meta_publish_discrepancy" as never).insert({ id: row.id, org_id: row.orgId, publish_operation_id: row.publishOperationId, publish_target_id: row.publishTargetId, provider_object_id: row.providerObjectId, discrepancy_type: row.discrepancyType, severity: row.severity, status: "open", detected_at: row.detectedAtIso, last_confirmed_at: row.lastConfirmedAtIso, evidence_count: 1, safe_summary: row.safeSummary, auto_repairable: row.autoRepairable } as never);
      return { ...row, evidenceCount: 1 };
    },
    async getDiscrepancy(orgId, id) { const r = await db().from("meta_publish_discrepancy" as never).select("*").eq("org_id", orgId).eq("id", id).maybeSingle(); return r.data ? discFromDb(r.data as Row) : null; },
    async listDiscrepancies(orgId) { const r = await db().from("meta_publish_discrepancy" as never).select("*").eq("org_id", orgId).order("detected_at", { ascending: false } as never); return ((r.data as Row[]) ?? []).map(discFromDb); },
    async updateDiscrepancy(row) { await db().from("meta_publish_discrepancy" as never).update({ status: row.status, resolution: row.resolution, resolved_by: row.resolvedBy, resolution_reason: row.resolutionReason, repaired_at: row.repairedAtIso, repaired_by: row.repairedBy, updated_at: now() } as never).eq("id", row.id); },
    async resolveOpenDiscrepancies(orgId, targetId, resolution) { const r = await db().from("meta_publish_discrepancy" as never).update({ status: "resolved", resolution, updated_at: now() } as never).eq("org_id", orgId).eq("publish_target_id", targetId).in("status", ["open", "monitoring"] as never).select("id"); return ((r.data as Row[]) ?? []).length; },
    async getTargetSnapshot(orgId, targetId) {
      const r = await db().from("meta_publish_target" as never).select("publish_operation_id, status, asset_id, platform, content_kind, provider_object_id, provider_container_id, provider_permalink, completed_at").eq("org_id", orgId).eq("id", targetId).maybeSingle();
      if (!r.data) return null; const t = r.data as Row;
      return { orgId, operationId: String(t.publish_operation_id), status: String(t.status), assetId: String(t.asset_id), platform: t.platform as TargetSnapshot["platform"], contentKind: String(t.content_kind), providerObjectId: (t.provider_object_id as string) ?? null, providerContainerId: (t.provider_container_id as string) ?? null, permalink: (t.provider_permalink as string) ?? null, publishedAtMs: t.completed_at ? Date.parse(String(t.completed_at)) : null };
    },
    async countMappingsForTarget(orgId, targetId) { const r = await db().from("meta_provider_object" as never).select("id", { count: "exact", head: true } as never).eq("org_id", orgId).eq("publish_target_id", targetId); return (r.count as number) ?? 0; },
    async createProviderObjectMapping(input) { const id = crypto.randomUUID(); await db().from("meta_provider_object" as never).insert({ id, org_id: input.orgId, publish_operation_id: input.operationId, publish_target_id: input.targetId, platform: input.platform, asset_id: input.assetId, provider_object_type: input.providerObjectType, external_object_id: input.externalObjectId, external_container_id: input.externalContainerId, permalink: input.permalink, provider_status: "published", created_time: now() } as never); return id; },
    async markTargetPublished(orgId, targetId, providerObjectId, permalink) { await db().from("meta_publish_target" as never).update({ status: "succeeded", provider_object_id: providerObjectId, provider_permalink: permalink, provider_verified: true, verification_status: "verified_published", last_verified_at: now(), updated_at: now() } as never).eq("org_id", orgId).eq("id", targetId); },
    async updateProviderObjectPermalink(orgId, providerObjectId, permalink) { await db().from("meta_provider_object" as never).update({ permalink, updated_at: now() } as never).eq("org_id", orgId).eq("id", providerObjectId); },
    async setTargetManualRetryEligible(orgId, targetId) { await db().from("meta_publish_target" as never).update({ retryable: true, verification_status: "confirmed_not_published", last_verified_at: now(), updated_at: now() } as never).eq("org_id", orgId).eq("id", targetId); },
    async setTargetVerified(orgId, targetId, state) { await db().from("meta_publish_target" as never).update({ provider_verified: state === "published" || state === "exists", verification_status: `verified_${state}`, last_verified_at: now(), updated_at: now() } as never).eq("org_id", orgId).eq("id", targetId); },
    async queueHealth(orgId, nowMs) {
      let q = db().from("meta_reconciliation_job" as never).select("status, available_at"); if (orgId) q = q.eq("org_id", orgId);
      const r = await q; const rows = (r.data as Row[]) ?? []; const by: Record<string, number> = {}; let oldest: number | null = null; let unresolved = 0;
      for (const x of rows) { const s = String(x.status); by[s] = (by[s] ?? 0) + 1; if (s === "unresolved") unresolved++; if ((s === "scheduled" || s === "available" || s === "retry_wait") && x.available_at) { const due = Date.parse(String(x.available_at)); if (due <= nowMs) { const age = nowMs - due; if (oldest == null || age > oldest) oldest = age; } } }
      const dl = orgId ? await db().from("meta_reconciliation_job" as never).select("id", { count: "exact", head: true } as never).eq("org_id", orgId).eq("status", "dead_letter") : await db().from("meta_reconciliation_job" as never).select("id", { count: "exact", head: true } as never).eq("status", "dead_letter");
      return { byStatus: by, deadLetter: (dl.count as number) ?? 0, oldestDueMs: oldest, unresolved };
    },
  };
}
