-- ============================================================================
-- ZONO — PHASE 34.2 · QA.1 RLS COVERAGE PACK. STRICTLY ADDITIVE + IDEMPOTENT.
-- ----------------------------------------------------------------------------
-- Closes the QA.1 finding that many private tables lacked an explicit RLS
-- enablement. For every private, org-scoped table this:
--   (1) enables row level security (no-op if already enabled), and
--   (2) adds a UNIQUELY-NAMED "<table>_qa1_read" permissive SELECT policy
--       scoped to the caller's org via public.current_org_id().
-- Permissive policies OR together, so this can NEVER reduce access below an
-- existing policy; it only closes gaps where RLS/read-scoping was missing.
-- Writes continue to run under service_role (BYPASSRLS) per the canonical rule,
-- so NO insert/update/delete policies are added here (matches house pattern).
-- Public reference tables and no-tenant-column tables are intentionally skipped
-- (documented in the phase report and below).
-- Re-runnable: drop policy if exists guards every policy.
-- ============================================================================

do $$
declare r record;
begin
  for r in (
    select * from (values
      ('acquisition_signals','org_id'),
      ('activities','org_id'),
      ('activity_events','org_id'),
      ('agencies','organization_id'),
      ('agency_agents','organization_id'),
      ('agency_ai_feedback','organization_id'),
      ('agency_aliases','organization_id'),
      ('agency_branches','organization_id'),
      ('agency_entity_relationships','organization_id'),
      ('agency_identity_matches','organization_id'),
      ('agency_intelligence_audit_log','organization_id'),
      ('agency_intelligence_job_runs','organization_id'),
      ('agency_intelligence_policies','organization_id'),
      ('agency_intelligence_reports','organization_id'),
      ('agency_intelligence_sources','organization_id'),
      ('agency_profiles','organization_id'),
      ('agency_report_exports','organization_id'),
      ('agency_resolution_candidates','organization_id'),
      ('agency_scores','organization_id'),
      ('agency_signals','organization_id'),
      ('agency_territory_stats','organization_id'),
      ('agency_timeline','organization_id'),
      ('agent_coaching_signals','organization_id'),
      ('agent_intelligence_profiles','organization_id'),
      ('agent_locality_performance','organization_id'),
      ('agent_property_type_performance','organization_id'),
      ('agent_website_events','organization_id'),
      ('agent_website_leads','organization_id'),
      ('agent_websites','organization_id'),
      ('ai_briefs','organization_id'),
      ('ai_copilot_cache','org_id'),
      ('ai_focus_items','organization_id'),
      ('ai_growth_plans','organization_id'),
      ('ai_memory','organization_id'),
      ('ai_mission_drafts','organization_id'),
      ('ai_opportunities','organization_id'),
      ('ai_risks','organization_id'),
      ('ai_simulations','organization_id'),
      ('attention_items','org_id'),
      ('audit_log','organization_id'),
      ('automation_actions','organization_id'),
      ('automation_conditions','organization_id'),
      ('automation_recommendations','organization_id'),
      ('automation_run_logs','organization_id'),
      ('automation_runs','organization_id'),
      ('automation_steps','organization_id'),
      ('automation_triggers','organization_id'),
      ('automation_workflows','organization_id'),
      ('automations','org_id'),
      ('beta_enrollments','org_id'),
      ('bi_reports','org_id'),
      ('bi_snapshots','org_id'),
      ('brand_assets','org_id'),
      ('brand_identity_profiles','org_id'),
      ('broker_ai_coaching','organization_id'),
      ('broker_aliases','org_id'),
      ('broker_competitive_intelligence','organization_id'),
      ('broker_discovery_runs','org_id'),
      ('broker_gap_analysis','organization_id'),
      ('broker_growth_strategy','organization_id'),
      ('broker_logo_assets','org_id'),
      ('broker_market_intelligence','organization_id'),
      ('broker_match_reviews','org_id'),
      ('broker_profiles','org_id'),
      ('broker_service_areas','org_id'),
      ('broker_sources','org_id'),
      ('broker_winning_dna','organization_id'),
      ('brokerage_external_listing_links','organization_id'),
      ('brokerage_office_discovery_runs','organization_id'),
      ('brokerage_research_jobs','organization_id'),
      ('building_cluster_profiles','organization_id'),
      ('building_intelligence','organization_id'),
      ('buyer_commitments','org_id'),
      ('buyer_demand_profiles','org_id'),
      ('buyer_financial_profiles','organization_id'),
      ('buyer_geo_profiles','org_id'),
      ('buyer_intelligence_profiles','org_id'),
      ('buyer_missions','org_id'),
      ('buyer_objections','org_id'),
      ('buyer_property_matches','org_id'),
      ('buyer_risks','org_id'),
      ('buyer_segments','organization_id'),
      ('buyer_touchpoints','org_id'),
      ('buyers','org_id'),
      ('client_advocates','organization_id'),
      ('client_memory','org_id'),
      ('client_portal_items','organization_id'),
      ('client_portal_sections','organization_id'),
      ('client_portal_views','organization_id'),
      ('client_portals','organization_id'),
      ('client_reviews','organization_id'),
      ('communication_commitments','org_id'),
      ('communication_entities','org_id'),
      ('communication_events','org_id'),
      ('communication_followups','org_id'),
      ('communication_insights','org_id'),
      ('communication_intelligence_profiles','org_id'),
      ('communication_intents','org_id'),
      ('communication_messages','org_id'),
      ('communication_objections','org_id'),
      ('communication_opportunities','org_id'),
      ('communication_risks','org_id'),
      ('communication_sentiment','org_id'),
      ('communication_summaries','org_id'),
      ('communication_threads','org_id'),
      ('community_activity_logs','organization_id'),
      ('community_comments','organization_id'),
      ('community_deal_attribution','organization_id'),
      ('community_discovery_candidates','organization_id'),
      ('community_discovery_runs','organization_id'),
      ('community_dna_profiles','organization_id'),
      ('community_intelligence_profiles','organization_id'),
      ('community_lead_attribution','organization_id'),
      ('community_metrics','organization_id'),
      ('community_network_profiles','organization_id'),
      ('community_profiles','organization_id'),
      ('community_rankings','organization_id'),
      ('competitor_market_positions','organization_id'),
      ('competitor_profiles','organization_id'),
      ('competitor_signals','organization_id'),
      ('conversation_memory','org_id'),
      ('creative_dna_analysis_runs','org_id'),
      ('creative_dna_profiles','org_id'),
      ('creative_generation_attempts','org_id'),
      ('creative_generation_references','org_id'),
      ('creative_generations','org_id'),
      ('creative_qa_reports','org_id'),
      ('creative_reference_assets','org_id'),
      ('daily_distribution_batches','organization_id'),
      ('daily_distribution_items','organization_id'),
      ('deal_forecast_signals','organization_id'),
      ('deal_forecasts','organization_id'),
      ('deal_journeys','organization_id'),
      ('deal_negotiations','organization_id'),
      ('deal_objections','organization_id'),
      ('deal_profiles','organization_id'),
      ('deal_tasks','organization_id'),
      ('deals','org_id'),
      ('decision_intelligence_profiles','org_id'),
      ('decision_queue','org_id'),
      ('decision_recommendations','org_id'),
      ('demand_cluster_buyers','org_id'),
      ('demand_clusters','org_id'),
      ('demand_heatmap_cells','org_id'),
      ('distribution_analytics','org_id'),
      ('distribution_automations','org_id'),
      ('distribution_campaign_groups','org_id'),
      ('distribution_campaigns','org_id'),
      ('distribution_channels','org_id'),
      ('distribution_comments','org_id'),
      ('distribution_group_leads','org_id'),
      ('distribution_group_posts','org_id'),
      ('distribution_groups','org_id'),
      ('distribution_leads','org_id'),
      ('distribution_opportunity_signals','organization_id'),
      ('distribution_plan_items','organization_id'),
      ('distribution_plans','organization_id'),
      ('distribution_posts','org_id'),
      ('distribution_provider_connections','org_id'),
      ('distribution_provider_destinations','org_id'),
      ('distribution_publish_jobs','org_id'),
      ('distribution_queue','organization_id'),
      ('distribution_schedules','org_id'),
      ('distribution_variations','org_id'),
      ('document_audit_logs','organization_id'),
      ('document_checklists','organization_id'),
      ('document_folders','organization_id'),
      ('document_participants','organization_id'),
      ('document_requests','organization_id'),
      ('document_requirements','organization_id'),
      ('document_signatures','organization_id'),
      ('document_templates','organization_id'),
      ('document_versions','organization_id'),
      ('documents','org_id'),
      ('engine_runs','organization_id'),
      ('entity_relationships','org_id'),
      ('explainability_events','org_id'),
      ('external_listing_duplicates','org_id'),
      ('external_listing_history','org_id'),
      ('external_listing_sources','org_id'),
      ('external_listings','org_id'),
      ('facebook_connection_paths','org_id'),
      ('facebook_extension_instances','org_id'),
      ('facebook_extension_pairings','org_id'),
      ('financing_signals','organization_id'),
      ('geo_coverage_targets','organization_id'),
      ('graph_entities','organization_id'),
      ('graph_relationships','organization_id'),
      ('graph_signals','organization_id'),
      ('import_job_logs','org_id'),
      ('import_jobs','org_id'),
      ('inventory_acquisition_actions','organization_id'),
      ('inventory_acquisition_profiles','organization_id'),
      ('inventory_acquisition_reviews','organization_id'),
      ('journey_audit_log','org_id'),
      ('journey_blockers','org_id'),
      ('journey_delayed_actions','org_id'),
      ('journey_events','org_id'),
      ('journey_execution_steps','org_id'),
      ('journey_executions','org_id'),
      ('journey_milestones','org_id'),
      ('journey_opportunities','org_id'),
      ('journey_predictions','org_id'),
      ('journey_risks','org_id'),
      ('journey_scores','org_id'),
      ('journey_sla_rules','org_id'),
      ('journey_stages','org_id'),
      ('journey_templates','org_id'),
      ('journey_triggers','org_id'),
      ('journey_velocity','org_id'),
      ('journey_workflow_versions','org_id'),
      ('journey_workflows','org_id'),
      ('journeys','org_id'),
      ('lead_routing_candidates','organization_id'),
      ('lead_routing_profiles','organization_id'),
      ('leads','org_id'),
      ('legal_documents','organization_id'),
      ('mai_model_calibration','organization_id'),
      ('management_actions','organization_id'),
      ('market_acceptance_aggregates','organization_id'),
      ('market_acceptance_scores','organization_id'),
      ('market_area_leaders','organization_id'),
      ('market_area_snapshots','organization_id'),
      ('market_listing_events','organization_id'),
      ('market_listing_lifecycle','organization_id'),
      ('market_listing_signals','organization_id'),
      ('marketing_opportunity_signals','organization_id'),
      ('match_intelligence_profiles','org_id'),
      ('match_objections','org_id'),
      ('match_opportunities','org_id'),
      ('match_risks','org_id'),
      ('matching_results','org_id'),
      ('meetings','org_id'),
      ('messenger_threads','organization_id'),
      ('notes','org_id'),
      ('notification_state','organization_id'),
      ('notifications','org_id'),
      ('office_coaching_items','org_id'),
      ('office_goals','org_id'),
      ('office_intelligence_profiles','organization_id'),
      ('office_intelligence_snapshots','org_id'),
      ('office_reports','org_id'),
      ('office_website_events','organization_id'),
      ('office_website_leads','organization_id'),
      ('office_websites','organization_id'),
      ('onboarding_progress','org_id'),
      ('opportunities','org_id'),
      ('opportunity_signals','org_id'),
      ('org_invitations','org_id'),
      ('org_market_property_links','org_id'),
      ('org_plans','org_id'),
      ('organization_operating_localities','organization_id'),
      ('organization_revenue_profiles','organization_id'),
      ('pipeline_snapshots','organization_id'),
      ('platform_audit_log','org_id'),
      ('projects','org_id'),
      ('properties','org_id'),
      ('property_alerts','org_id'),
      ('property_broker_matches','org_id'),
      ('property_calendar_plans','org_id'),
      ('property_community_matches','organization_id'),
      ('property_exposure_channels','org_id'),
      ('property_intelligence_profiles','org_id'),
      ('property_journeys','org_id'),
      ('property_levers','org_id'),
      ('property_marketing_profiles','organization_id'),
      ('property_media','org_id'),
      ('property_missions','org_id'),
      ('property_opportunity_scores','org_id'),
      ('property_radar_settings','org_id'),
      ('property_research_reports','organization_id'),
      ('property_risks','org_id'),
      ('property_score_events','org_id'),
      ('property_seller_touchpoints','org_id'),
      ('property_sellers','org_id'),
      ('property_sync_runs','org_id'),
      ('property_sync_sources','org_id'),
      ('property_sync_watermarks','org_id'),
      ('property_transactions','organization_id'),
      ('property_valuations','organization_id'),
      ('radar_competitor_alerts','org_id'),
      ('radar_competitor_area_metrics','org_id'),
      ('radar_competitor_listing_links','org_id'),
      ('radar_competitor_profiles','org_id'),
      ('radar_seller_followups','org_id'),
      ('radar_seller_outcomes','org_id'),
      ('radar_seller_profiles','org_id'),
      ('radar_seller_signals','org_id'),
      ('radar_seller_touchpoints','org_id'),
      ('rain_edges','organization_id'),
      ('rain_nodes','organization_id'),
      ('recommendation_events','organization_id'),
      ('recommendation_feedback','organization_id'),
      ('recommendation_map_points','organization_id'),
      ('recommendation_packages','organization_id'),
      ('recommendation_profiles','organization_id'),
      ('recommendations','organization_id'),
      ('referrals','organization_id'),
      ('reputation_scores','organization_id'),
      ('reputation_signals','organization_id'),
      ('revenue_leakage_events','organization_id'),
      ('revenue_signals','org_id'),
      ('revenue_targets','organization_id'),
      ('review_campaigns','organization_id'),
      ('review_requests','organization_id'),
      ('seller_commitments','org_id'),
      ('seller_geo_profiles','org_id'),
      ('seller_intelligence_profiles','org_id'),
      ('seller_missions','org_id'),
      ('seller_risks','org_id'),
      ('seller_touchpoints','org_id'),
      ('sellers','org_id'),
      ('social_account_sync_logs','organization_id'),
      ('social_accounts','organization_id'),
      ('social_connection_vault','organization_id'),
      ('social_followups','organization_id'),
      ('social_interactions','organization_id'),
      ('social_leads','organization_id'),
      ('street_intelligence','organization_id'),
      ('street_territory_profiles','organization_id'),
      ('support_impersonation_log','org_id'),
      ('tasks','org_id'),
      ('team_intelligence_profiles','organization_id'),
      ('team_opportunity_leaks','organization_id'),
      ('team_performance_snapshots','organization_id'),
      ('territory_assignments','organization_id'),
      ('territory_centroids','org_id'),
      ('territory_dna_profiles','organization_id'),
      ('territory_profiles','organization_id'),
      ('territory_signals','organization_id'),
      ('territory_snapshots','organization_id'),
      ('transaction_opportunity_radar_alerts','organization_id'),
      ('transaction_sync_logs','organization_id'),
      ('units','org_id'),
      ('usage_events','org_id'),
      ('user_feedback','org_id'),
      ('users','org_id'),
      ('valuation_accuracy','organization_id'),
      ('valuation_adjustments','organization_id'),
      ('valuation_broker_sold_properties','organization_id'),
      ('valuation_comparables','organization_id'),
      ('valuation_explanations','organization_id'),
      ('valuation_history','organization_id'),
      ('valuation_market_snapshots','organization_id'),
      ('valuation_report_sends','organization_id'),
      ('valuation_reports','organization_id'),
      ('valuation_weight_results','organization_id'),
      ('whatsapp_accounts','organization_id'),
      ('whatsapp_ai_actions','organization_id'),
      ('whatsapp_audit_logs','organization_id'),
      ('whatsapp_call_events','organization_id'),
      ('whatsapp_campaigns','organization_id'),
      ('whatsapp_conversations','organization_id'),
      ('whatsapp_daily_missions','organization_id'),
      ('whatsapp_drafts','organization_id'),
      ('whatsapp_followups','organization_id'),
      ('whatsapp_knowledge_base','organization_id'),
      ('whatsapp_messages','organization_id'),
      ('whatsapp_segments','organization_id'),
      ('whatsapp_smart_link_events','organization_id'),
      ('whatsapp_smart_links','organization_id'),
      ('zi_conversations','organization_id'),
      ('zi_diagnostic_runs','organization_id'),
      ('zi_knowledge_feedback','organization_id'),
      ('zi_learning_progress','organization_id'),
      ('zi_messages','organization_id'),
      ('zono_agent_inbox','organization_id'),
      ('zono_agent_memory','organization_id'),
      ('zono_agent_performance','organization_id'),
      ('zono_agent_runs','organization_id'),
      ('zono_agents','organization_id'),
      ('zono_api_audit','organization_id'),
      ('zono_api_keys','organization_id'),
      ('zono_campaign_assets','org_id'),
      ('zono_campaigns','org_id'),
      ('zono_copy_assets','org_id'),
      ('zono_creative_assets','org_id'),
      ('zono_creative_candidates','org_id'),
      ('zono_creative_concepts','org_id'),
      ('zono_creative_outputs','org_id'),
      ('zono_creative_quality_reviews','org_id'),
      ('zono_marketing_analysis_jobs','org_id'),
      ('zono_marketing_assets','org_id'),
      ('zono_marketing_briefs','org_id'),
      ('zono_marketing_dna_profiles','org_id'),
      ('zono_marketing_feedback','org_id'),
      ('zono_missions','organization_id'),
      ('zono_orchestrator_locks','organization_id'),
      ('zono_orchestrator_runs','organization_id'),
      ('zono_quick_creative_outputs','org_id'),
      ('zono_quick_creative_requests','org_id'),
      ('zono_visual_assets','org_id'),
      ('zono_webhooks','organization_id'),
      ('zono_workflows','organization_id')
    ) as x(tbl, orgcol)
  ) loop
    -- enable RLS (idempotent)
    execute format('alter table public.%I enable row level security;', r.tbl);
    -- additive, uniquely-named org-scoped read policy
    execute format('drop policy if exists %I on public.%I;', r.tbl||'_qa1_read', r.tbl);
    execute format(
      'create policy %I on public.%I for select to authenticated using (%I = public.current_org_id());',
      r.tbl||'_qa1_read', r.tbl, r.orgcol);
  end loop;
end $$;

-- ── Intentionally SKIPPED — no tenant column (require manual review) ─────────
--   automation_templates
--   brokerage_activity_areas
--   brokerage_agents
--   brokerage_broker_identity
--   brokerage_change_log
--   brokerage_completeness
--   brokerage_contact_points
--   brokerage_coverage
--   brokerage_data_conflicts
--   brokerage_data_health_snapshots
--   brokerage_data_sources
--   brokerage_duplicate_cluster_members
--   brokerage_duplicate_clusters
--   brokerage_entity_dna
--   brokerage_entity_snapshots
--   brokerage_graph_edges
--   brokerage_graph_nodes
--   brokerage_identity_matches
--   brokerage_market_dna
--   brokerage_market_share
--   brokerage_neighborhood_stats
--   brokerage_office_candidates
--   brokerage_office_evidence
--   brokerage_office_graph_edges
--   brokerage_office_locations
--   brokerage_office_merge_suggestions
--   brokerage_offices
--   brokerage_predictions
--   brokerage_refresh_diffs
--   brokerage_refresh_runs
--   brokerage_relationship_discoveries
--   brokerage_research_dossier
--   brokerage_timeline_events
--   legal_document_audit_log
--   legal_document_signatures
--   legal_template_fields
--   legal_template_sections
--   legal_templates
--   market_area_cache_state
--   market_property_events
--   market_property_sources
--   market_sync_runs
--   market_sync_watermarks
--   neighborhood_enrichment_cities
--   organizations
--   provider_qa_daily_metrics
--   provider_schema_events
--   provider_schema_fingerprints
--   user_operating_localities
--   zono_workflow_history
--   zono_workflow_steps
