// ============================================================================
// 🌐 ZONO — Meta Workspace (Batch 6.9) · INSIGHTS STORE ADAPTER. Phase 2 (server).
// ----------------------------------------------------------------------------
// Supabase-backed InsightsStore (service-role writes; org-scoped reads). Insight
// snapshots are APPEND-ONLY — inserts only, never updates (the unique key makes a
// duplicate observation a no-op). The atomic claim reuses the SKIP LOCKED SQL
// function. No token, raw payload, or signed URL is stored.
// ============================================================================
import "server-only";
import crypto from "node:crypto";
import { createServiceRoleClient } from "@/lib/supabase/server";
import type { InsightsStore, InsightJobRow, RefreshStateRow, ObjectRef, AccountRef, InsightJobKind } from "./ports";
import type { InsightSnapshot, InsightSubjectKind, MetricKey, InsightPeriod } from "./domain";
import type { MetaPlatform } from "../types";

type Row = Record<string, unknown>;
const db = () => createServiceRoleClient();
const now = () => new Date().toISOString();

const jobToDb = (j: InsightJobRow): Row => ({ id: j.id, org_id: j.orgId, job_kind: j.jobKind, subject_kind: j.subjectKind, subject_ref: j.subjectRef, platform: j.platform, status: j.status, priority: j.priority, available_at: j.availableAtIso, attempt_count: j.attemptCount, max_attempts: j.maxAttempts, retry_budget_remaining: j.retryBudgetRemaining, requeue_count: j.requeueCount, lease_owner: j.leaseOwner, lease_token: j.leaseToken, lease_expires_at: j.leaseExpiresAtIso, heartbeat_at: j.heartbeatAtIso, claimed_at: j.claimedAtIso, started_at: j.startedAtIso, completed_at: j.completedAtIso, next_attempt_at: j.nextAttemptAtIso, last_error_kind: j.lastErrorKind, safe_last_error: j.safeLastError, correlation_id: j.correlationId, idempotency_key: j.idempotencyKey, updated_at: now() });
const jobFromDb = (d: Row): InsightJobRow => ({ id: String(d.id), orgId: String(d.org_id), jobKind: d.job_kind as InsightJobKind, subjectKind: d.subject_kind as InsightSubjectKind, subjectRef: String(d.subject_ref), platform: d.platform as MetaPlatform, status: d.status as InsightJobRow["status"], priority: Number(d.priority ?? 100), availableAtIso: String(d.available_at), attemptCount: Number(d.attempt_count ?? 0), maxAttempts: Number(d.max_attempts ?? 6), retryBudgetRemaining: Number(d.retry_budget_remaining ?? 6), requeueCount: Number(d.requeue_count ?? 0), leaseOwner: (d.lease_owner as string) ?? null, leaseToken: (d.lease_token as string) ?? null, leaseExpiresAtIso: (d.lease_expires_at as string) ?? null, heartbeatAtIso: (d.heartbeat_at as string) ?? null, claimedAtIso: (d.claimed_at as string) ?? null, startedAtIso: (d.started_at as string) ?? null, completedAtIso: (d.completed_at as string) ?? null, nextAttemptAtIso: (d.next_attempt_at as string) ?? null, lastErrorKind: (d.last_error_kind as string) ?? null, safeLastError: (d.safe_last_error as string) ?? null, correlationId: String(d.correlation_id ?? ""), idempotencyKey: String(d.idempotency_key ?? "") });
const snapFromDb = (d: Row): InsightSnapshot => ({ metricKey: d.metric_key as MetricKey, period: d.period as InsightPeriod, value: Number(d.metric_value ?? 0), observedAt: String(d.observed_at) });

export function createSupabaseInsightsStore(): InsightsStore {
  return {
    async appendObjectSnapshots(orgId, poid, platform, snaps, jobId) { if (snaps.length === 0) return 0; const rows = snaps.map((s) => ({ id: crypto.randomUUID(), org_id: orgId, provider_object_id: poid, platform, metric_key: s.metricKey, period: s.period, metric_value: s.value, observed_at: s.observedAt, evidence_kind: "provider_inspection", source_refresh_job_id: jobId })); await db().from("meta_object_insight" as never).upsert(rows as never, { onConflict: "org_id,provider_object_id,metric_key,period,observed_at", ignoreDuplicates: true } as never); return rows.length; },
    async appendAccountSnapshots(orgId, assetId, platform, snaps, jobId) { if (snaps.length === 0) return 0; const rows = snaps.map((s) => ({ id: crypto.randomUUID(), org_id: orgId, asset_id: assetId, platform, metric_key: s.metricKey, period: s.period, metric_value: s.value, observed_at: s.observedAt, evidence_kind: "provider_inspection", source_refresh_job_id: jobId })); await db().from("meta_account_insight" as never).upsert(rows as never, { onConflict: "org_id,asset_id,metric_key,period,observed_at", ignoreDuplicates: true } as never); return rows.length; },
    async getRefreshState(orgId, subjectKind, subjectRef) { const r = await db().from("meta_insight_refresh_state" as never).select("*").eq("org_id", orgId).eq("subject_kind", subjectKind).eq("subject_ref", subjectRef).maybeSingle(); if (!r.data) return null; const d = r.data as Row; return { subjectKind, subjectRef, platform: d.platform as MetaPlatform, firstObservedAtIso: (d.first_observed_at as string) ?? null, lastRefreshedAtIso: (d.last_refreshed_at as string) ?? null, nextRefreshAtIso: (d.next_refresh_at as string) ?? null, refreshCount: Number(d.refresh_count ?? 0), quiesced: Boolean(d.quiesced) }; },
    async upsertRefreshState(orgId, row: RefreshStateRow) { const found = await db().from("meta_insight_refresh_state" as never).select("id").eq("org_id", orgId).eq("subject_kind", row.subjectKind).eq("subject_ref", row.subjectRef).maybeSingle(); const body = { org_id: orgId, subject_kind: row.subjectKind, subject_ref: row.subjectRef, platform: row.platform, first_observed_at: row.firstObservedAtIso, last_refreshed_at: row.lastRefreshedAtIso, next_refresh_at: row.nextRefreshAtIso, refresh_count: row.refreshCount, quiesced: row.quiesced, updated_at: now() }; if (found.data) await db().from("meta_insight_refresh_state" as never).update(body as never).eq("id", String((found.data as { id: string }).id)); else await db().from("meta_insight_refresh_state" as never).insert({ id: crypto.randomUUID(), ...body, created_at: now() } as never); },
    async objectRef(orgId, poid): Promise<ObjectRef | null> { const r = await db().from("meta_provider_object" as never).select("external_object_id, asset_id, platform").eq("org_id", orgId).eq("id", poid).maybeSingle(); if (!r.data) return null; const d = r.data as Row; return { objectExternalId: String(d.external_object_id), assetId: String(d.asset_id), platform: d.platform as MetaPlatform }; },
    async accountRef(orgId, assetId): Promise<AccountRef | null> { const pg = await db().from("meta_page" as never).select("external_id").eq("org_id", orgId).eq("id", assetId).maybeSingle(); if (pg.data) return { assetExternalId: String((pg.data as Row).external_id), platform: "facebook" }; const ig = await db().from("meta_instagram_account" as never).select("external_id").eq("org_id", orgId).eq("id", assetId).maybeSingle(); if (ig.data) return { assetExternalId: String((ig.data as Row).external_id), platform: "instagram" }; return null; },
    async listObjectSeries(orgId, poid) { const r = await db().from("meta_object_insight" as never).select("metric_key, period, metric_value, observed_at").eq("org_id", orgId).eq("provider_object_id", poid).order("observed_at", { ascending: true } as never); return ((r.data as Row[]) ?? []).map(snapFromDb); },
    async listAccountSeries(orgId, assetId) { const r = await db().from("meta_account_insight" as never).select("metric_key, period, metric_value, observed_at").eq("org_id", orgId).eq("asset_id", assetId).order("observed_at", { ascending: true } as never); return ((r.data as Row[]) ?? []).map(snapFromDb); },
    async insertJob(row) { await db().from("meta_insight_refresh_job" as never).insert({ ...jobToDb(row), created_at: now() } as never); },
    async getJob(orgId, id) { const r = await db().from("meta_insight_refresh_job" as never).select("*").eq("org_id", orgId).eq("id", id).maybeSingle(); return r.data ? jobFromDb(r.data as Row) : null; },
    async findJobByIdem(orgId, key) { const r = await db().from("meta_insight_refresh_job" as never).select("*").eq("org_id", orgId).eq("idempotency_key", key).maybeSingle(); return r.data ? jobFromDb(r.data as Row) : null; },
    async findActiveJob(orgId, subjectKind, subjectRef) { const r = await db().from("meta_insight_refresh_job" as never).select("*").eq("org_id", orgId).eq("subject_kind", subjectKind).eq("subject_ref", subjectRef).in("status", ["scheduled", "available", "claimed", "executing", "retry_wait"] as never).maybeSingle(); return r.data ? jobFromDb(r.data as Row) : null; },
    async updateJob(row) { await db().from("meta_insight_refresh_job" as never).update(jobToDb(row) as never).eq("id", row.id); },
    async claimDueJobs(args) { const r = await db().rpc("meta_insight_claim_due" as never, { p_now: new Date(args.nowMs).toISOString(), p_limit: args.limit, p_per_org_max: args.perOrgMax, p_lease_owner: args.leaseOwner, p_lease_seconds: args.leaseSeconds } as never); return ((r.data as unknown as Row[]) ?? []).map(jobFromDb); },
    async findStaleJobs(nowMs, limit) { const r = await db().from("meta_insight_refresh_job" as never).select("*").in("status", ["claimed", "executing"] as never).lte("lease_expires_at", new Date(nowMs).toISOString()).limit(limit); return ((r.data as Row[]) ?? []).map(jobFromDb); },
    async countInFlight() { const r = await db().from("meta_insight_refresh_job" as never).select("org_id").in("status", ["claimed", "executing"] as never); const rows = (r.data as Row[]) ?? []; const per: Record<string, number> = {}; for (const x of rows) { const o = String(x.org_id); per[o] = (per[o] ?? 0) + 1; } return { global: rows.length, perOrg: per }; },
    async queueHealth(orgId, nowMs) { let q = db().from("meta_insight_refresh_job" as never).select("status, available_at"); if (orgId) q = q.eq("org_id", orgId); const r = await q; const rows = (r.data as Row[]) ?? []; const by: Record<string, number> = {}; let oldest: number | null = null; for (const x of rows) { const s = String(x.status); by[s] = (by[s] ?? 0) + 1; if ((s === "scheduled" || s === "available" || s === "retry_wait") && x.available_at) { const due = Date.parse(String(x.available_at)); if (due <= nowMs) { const age = nowMs - due; if (oldest == null || age > oldest) oldest = age; } } } return { byStatus: by, deadLetter: by.dead_letter ?? 0, oldestDueMs: oldest }; },
  };
}
